api_platform:
    title: API Vite et Gourmand
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: false